### ISSUE TITLE
xmacro for no x server running? (huh)

### ISSUE THREAD

**Issue by sandric** [alvatar/xmacro#1]
May sound stupid, but i'm searching for xmacro without 'x' at start. I mean I need to grab keypresses and delays with xmacrorec2 to file and then replay it from that file with xmacroplay, but being not in xsession, but in raw tty instead. Sanity, library api calls and name of lib itself made clear for me that it won'd work in naked terminal, but I tried and get

`xmacrorec2: could not open display "", aborting.`

Any help? thanks.

**Comment by alvatar** [comment]
How would you use xmacro if not within an X session? It is intended to emulate X input, so I don't think you can make it work without the X. Also, as you mention, API calls make it clear.
Anyway, maybe there is an advanced way I'm not aware of, but this is an old project and I can't really recall the details ATM.

**Comment by sandric** [comment]
Yes, I know all that. I just hoped you know alternative command to do all this without X session, emulating not X input but tty input maybe?

**Comment by alvatar** [comment]
No idea! Can't help you, sorry.
